- modelo: Random Forest (Inicial)
  tipo: ml
  hiperparametros:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
    n_jobs: -1
    verbose: 1
  n_features: 93
  metricas:
    train:
      RMSE: 34654.62036994202
      MAE: 24358.500177949845
      R2: 0.8266185630758178
    test:
      RMSE: 37576.46299414727
      MAE: 26345.70256987982
      R2: 0.7922761701733803
    overfitting_ratio: 1.084313219796213
  notebook: 03_modelos_ml_clean.ipynb
- modelo: Random Forest (Optimizado)
  tipo: ml
  hiperparametros:
    n_estimators: 200
    min_samples_split: 10
    min_samples_leaf: 2
    max_features: sqrt
    max_depth: 20
    bootstrap: true
  n_features: 93
  metricas:
    train:
      RMSE: 40979.18341991563
      MAE: 28960.750601214775
      R2: 0.7575585310186809
    test:
      RMSE: 40837.38296513559
      MAE: 28963.261171253485
      R2: 0.7546588875314967
    overfitting_ratio: 0.9965396954515418
  notebook: 03_modelos_ml_clean.ipynb
- modelo: XGBoost (Inicial)
  tipo: ml
  hiperparametros:
    objective: reg:squarederror
    base_score: null
    booster: null
    callbacks: null
    colsample_bylevel: null
    colsample_bynode: null
    colsample_bytree: 0.8
    device: null
    early_stopping_rounds: null
    enable_categorical: false
    eval_metric: rmse
    feature_types: null
    gamma: null
    grow_policy: null
    importance_type: null
    interaction_constraints: null
    learning_rate: 0.1
    max_bin: null
    max_cat_threshold: null
    max_cat_to_onehot: null
    max_delta_step: null
    max_depth: 6
    max_leaves: null
    min_child_weight: null
    missing: .nan
    monotone_constraints: null
    multi_strategy: null
    n_estimators: 100
    n_jobs: -1
    num_parallel_tree: null
    random_state: 42
    reg_alpha: 0
    reg_lambda: 1
    sampling_method: null
    scale_pos_weight: null
    subsample: 0.8
    tree_method: null
    validate_parameters: null
    verbosity: 1
  n_features: 93
  metricas:
    train:
      RMSE: 37353.1265625784
      MAE: 26179.712890625
      R2: 0.7985653281211853
    test:
      RMSE: 37466.61276389954
      MAE: 26235.5078125
      R2: 0.7934889197349548
    overfitting_ratio: 1.0030381981848564
  notebook: 03_modelos_ml_clean.ipynb
- modelo: XGBoost (Optimizado)
  tipo: ml
  hiperparametros:
    subsample: 0.7
    reg_lambda: 1
    reg_alpha: 0.1
    n_estimators: 300
    max_depth: 8
    learning_rate: 0.1
    colsample_bytree: 1.0
  n_features: 93
  metricas:
    train:
      RMSE: 32188.832846190617
      MAE: 22516.638671875
      R2: 0.8504140973091125
    test:
      RMSE: 34622.80219739587
      MAE: 23967.03125
      R2: 0.8236485719680786
    overfitting_ratio: 1.0756153341388797
  notebook: 03_modelos_ml_clean.ipynb
- modelo: Red Neuronal (Inicial)
  tipo: ml
  hiperparametros:
    activation: relu
    alpha: 0.01
    batch_size: auto
    beta_1: 0.9
    beta_2: 0.999
    early_stopping: true
    epsilon: 1.0e-08
    hidden_layer_sizes:
    - 50
    - 25
    learning_rate: adaptive
    learning_rate_init: 0.001
    loss: squared_error
    max_fun: 15000
    max_iter: 200
    momentum: 0.9
    n_iter_no_change: 10
    nesterovs_momentum: true
    power_t: 0.5
    random_state: 42
    shuffle: true
    solver: adam
    tol: 0.0001
    validation_fraction: 0.1
    verbose: true
    warm_start: false
  n_features: 93
  metricas:
    train:
      RMSE: 38812.82188125086
      MAE: 26959.634723309704
      R2: 0.7825142808262959
    test:
      RMSE: 38640.94405754755
      MAE: 26824.362119441383
      R2: 0.7803405048061879
    overfitting_ratio: 0.995571622588299
  notebook: 03_modelos_ml_clean.ipynb
- modelo: Red Neuronal (Optimizada)
  tipo: ml
  hiperparametros:
    cv: 2
    error_score: .nan
    estimator__activation: relu
    estimator__alpha: 0.0001
    estimator__batch_size: auto
    estimator__beta_1: 0.9
    estimator__beta_2: 0.999
    estimator__early_stopping: true
    estimator__epsilon: 1.0e-08
    estimator__hidden_layer_sizes:
    - 100
    estimator__learning_rate: constant
    estimator__learning_rate_init: 0.001
    estimator__loss: squared_error
    estimator__max_fun: 15000
    estimator__max_iter: 100
    estimator__momentum: 0.9
    estimator__n_iter_no_change: 10
    estimator__nesterovs_momentum: true
    estimator__power_t: 0.5
    estimator__random_state: 42
    estimator__shuffle: true
    estimator__solver: adam
    estimator__tol: 0.0001
    estimator__validation_fraction: 0.1
    estimator__verbose: false
    estimator__warm_start: false
    estimator: !!python/object:sklearn.neural_network._multilayer_perceptron.MLPRegressor
      activation: relu
      solver: adam
      alpha: 0.0001
      batch_size: auto
      learning_rate: constant
      learning_rate_init: 0.001
      power_t: 0.5
      max_iter: 100
      loss: squared_error
      hidden_layer_sizes: !!python/tuple
      - 100
      shuffle: true
      random_state: 42
      tol: 0.0001
      verbose: false
      warm_start: false
      momentum: 0.9
      nesterovs_momentum: true
      early_stopping: true
      validation_fraction: 0.1
      beta_1: 0.9
      beta_2: 0.999
      epsilon: 1.0e-08
      n_iter_no_change: 10
      max_fun: 15000
      _sklearn_version: 1.7.0
    n_jobs: -1
    param_grid:
      hidden_layer_sizes:
      - - 100
      - - 50
        - 25
      activation:
      - relu
      alpha:
      - 0.0001
      learning_rate_init:
      - 0.001
    pre_dispatch: 2*n_jobs
    refit: true
    return_train_score: false
    scoring: neg_root_mean_squared_error
    verbose: 2
  n_features: 93
  metricas:
    train:
      RMSE: 40645.58914189069
      MAE: 28414.42769823723
      R2: 0.761489692497789
    test:
      RMSE: 40321.12255526895
      MAE: 28230.69488346782
      R2: 0.7608228131244332
    overfitting_ratio: 0.9920171759477012
  notebook: 03_modelos_ml_clean.ipynb
